baseURL = "https://goern.github.io/osg-dairy/"
languageCode = "en-us"
DefaultContentLanguage = "en" # Theme's display language, supports: en, fr, zh, zh-hant
title = "the diary"
copyright = "Copyright © 2022 Red Hat, Inc."

theme = "diary"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = "continuous information of Open Services Group"

enableOpenGraph = true
enableTwitterCards = true
title = "The Open Services Group dairy"
description = "please visite us at https://github.com/open-services-group/community/blob/main/README.md"

[taxonomies]
   tag = "tags"

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 1