languageCode = "en-us"
baseURL = "https://goern.github.io/osg-dairy/"
title = "Open Services Group dairy"
copyright = "Copyright © 2022 Red Hat, Inc."

theme = "PaperMod"
paginate = 5
enableInlineShortcodes = true
enableRobotsTXT = true
enableEmoji = true

[minify]
disableXML = true
minifyOutput = true

[params]
description = "continuous information from the Open Services Group"
env = "production"
author = "the Open Services Group authors"
images = [ "https://avatars.githubusercontent.com/u/94559058" ]
defaultTheme = "auto"
disableThemeToggle = false 
ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true 
ShowShareButtons = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true 
tocopen = false 

[params.homeInfoParams]
Title = "👋 The Open Services Group diary"
Content = "this is where we post short updates of our SIG, working group, or subproject activities..."

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/operatefirst"

[[params.socialIcons]]
name = "github"
url = "https://github.com/open-services-group"

[[menu.main]]
identifier = "tags"
name = "labels"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "search"
name = "search"
url = "/search/"
weight = 31

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services.twitter]
disableInlineCSS = true